### ISSUE TITLE
Исключение 'Could not connect to api, check your ID and SECRET', вызванное устаревшими сертификатами на сервере

### ISSUE THREAD

**Issue by Isk1n** [sendpulse/sendpulse-rest-api-php#1]
На хостингах, где давно ничего не обновлялось, при использовании этой библиотеки может вылезти исключение 'Could not connect to api, check your ID and SECRET', при этом ни ID, ни SECRET не виноваты. А виноват curl, который не в состоянии верифицировать сертификат. Чтобы обойти эту неприятность можно использовать опцию

``` php
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, FALSE);
```

**Comment by sendpulse** [comment]
добавили
