### ISSUE TITLE
Braking changes

### ISSUE THREAD

**Issue by webmoder** [sendpulse/sendpulse-rest-api-php#12]
**Ребята**, а давайте начнем **версионировать изменения нарушающие обратную совместимость**.
Это не первый раз, у нас прод падает 😢

**Comment by qzmenko** [comment]
Поддерживаю. У людей модуль для Drupal не заводится, из-за некоторых последних правок.

**Comment by ZL0D3Y** [comment]
В дальнейших релизах будет использоватся версионность, включая минорные изменения. 
Просьба описать, что именнно сломалось.

**Comment by webmoder** [comment]
Could not scan for classes inside "vendor/sendpulse/sendpulse-rest-api-php/api/" which does not appear to be a file nor a folder

**Comment by ZL0D3Y** [comment]
Sorry for troubles!

**Comment by ZL0D3Y** [comment]
Sorry for the inconvenience.
Fixed in version 1.0.1.
