### ISSUE TITLE
Send SMS

### ISSUE THREAD

**Issue by noecodjo** [sendpulse/sendpulse-rest-api-php#19]
Hi, thank for the work
How can i send sms to any mobile from this api

**Comment by YulKard** [comment]
Hi, I have a same question. I didn't found the method for that.
Thank you for advance.

**Comment by noecodjo** [comment]
hi, thank for this reply. I will do some research on my side

**Comment by artemmihelson** [comment]
Hi,

As I can see from the documentation, SendPulse has SMS Service. However code of PHP api clearly states there is no integration with SMS service there yet. How do I use it? When it's gonna be available? Or should I write wrapper by myself?

**Comment by sendpulse** [comment]
Find please all methods with 'sms' in ApiClient.php file.
This is enough for your purposes.
