### ISSUE TITLE
composer?

### ISSUE THREAD

**Issue by aleksanderd** [sendpulse/sendpulse-rest-api-php#2]
https://packagist.org/search/?q=sendpulse
No packages found :(
Почему бы не сделать простенький composer.json чтобы можно было устанавливать по "модному"? :)

ЗЫ. А вообще, спасибо! Не часто увидишь такую доступность по API, а где то даже примеров не выпросишь, а только махровые совковые инструкции. Молодцы!

**Comment by garethtdavies** [comment]
+1 for this. Can you add composer support?

**Comment by garethtdavies** [comment]
Until officially supported I added one here https://packagist.org/packages/wensleydale/sendpulse-rest-api-php

**Comment by Keanor** [comment]
https://github.com/sendpulse/sendpulse-rest-api-php/pull/5 composer support

**Comment by mesilov** [comment]
add composer

**Comment by sendpulse** [comment]
done https://packagist.org/packages/sendpulse/rest-api#1.0
