### ISSUE TITLE
Точно нужно ");" в примере?

### ISSUE THREAD

**Issue by jon4god** [sendpulse/sendpulse-rest-api-php#20]
В этом месте:
    )
);
var_dump($SPApiClient

Одна скобка лишняя?

**Comment by ZL0D3Y** [comment]
В этом это в каком? Файл? строка?

**Comment by jon4god** [comment]
README.md

два раза лишняя ")" в примерах.

**Comment by burre** [comment]
Номер строки в файле?

**Comment by jon4god** [comment]
47 лишняя ")"

**Comment by burre** [comment]
![image](https://user-images.githubusercontent.com/206959/35385722-f2187356-01d1-11e8-8053-6c05a45d01bd.png)
Специально для вас проверил PHP-линтером - в файле примеров нет ошибок.

**Comment by jon4god** [comment]
Круто! А я вот по старинке количество открытых и закрытых скобок

require 'vendor/autoload.php';

// Without Composer:
// require("your-path/sendpulse-rest-api-php/src/ApiInterface.php");
// require("your-path/sendpulse-rest-api-php/src/ApiClient.php");

use Sendpulse\RestApi\ApiClient;
use Sendpulse\RestApi\Storage\FileStorage;

// API credentials from https://login.sendpulse.com/settings/#api
define('API_USER_ID', '');
define('API_SECRET', '');
define('PATH_TO_ATTACH_FILE', __FILE__);

$SPApiClient = new ApiClient(API_USER_ID, API_SECRET, new FileStorage());

/*
 * Example: Get Mailing Lists
 */
var_dump($SPApiClient->listAddressBooks());

/*
 * Example: Add new email to mailing lists
 */
 $bookID = 123;
 $emails = array(
    array(
        'email' => 'subscriber@example.com',
        'variables' => array(
            'phone' => '+12345678900',
            'name' => 'User Name',
        )
    )
);
var_dump($SPApiClient->addEmails($bookID, $emails));

**Comment by jon4god** [comment]
Может лишнее углядел. Нервничаю.
