### ISSUE TITLE
А будет ли работать это без Сomposer?

### ISSUE THREAD

**Issue by jon4god** [sendpulse/sendpulse-rest-api-php#21]
Пробовал кто-то подключить это без Сomposer?
Такое ощущение, что тогда все связи рушатся.

**Comment by ZL0D3Y** [comment]
Его можно подключить и без composer, но тогда вам нужен какой-то загрузчик для неймспейсов, коим является composer и натравить его на сей пакет, но, имхо, зачем так над собой издеваться?

**Comment by jon4god** [comment]
Потому, что прикручиваю к проекту на wordpress. Так как формы подписки только на javascript, а шаблон тогда рушится. Вот и прикручиваю API в лоб. Все что нужно, отправить мыло в адресную книгу.

**Comment by ZL0D3Y** [comment]
https://roots.io/using-composer-with-wordpress/

**Comment by burre** [comment]
Попробуйте использовать плагин для вордпресса, который работает с формами.
https://ru.wordpress.org/plugins/sendpulse-email-marketing-newsletter/

**Comment by burre** [comment]
И что мешает вам, полученный короткий код формы вставить в плагин? Он все равно работает.

**Comment by jon4god** [comment]
Ок. Кто спорит. Плагин работает. На примере нужно.
http://kecu.ru/ Форма подписки рядом с футером. Мне там никакие JS-формы не нужны. Созданные форму туда не поместить без ломки дизайна (на внутренних страницах легко). Мне нужно просто отправить мыло в адресную книгу с главной через форму без перехода. Это и пытаюсь сделать через прикручивание API, но оно не подключается, поэтому сижу и копаю.

**Comment by burre** [comment]
@jon4god 
>То, что API в сайт работающий встроить сложно, так чьи это проблемы. Учись. Буду учиться. Но на >мой взгляд API не только под новые проекты должен быть, которые ты собираешь как тебе >вздумается. Должна быть вариативность. 

Код враппера для API вам доступен. Вы можете скопировать его и переписать под свои нужны - убрать неймспейсы, сделать ручные реквайры и все чего захотите. 

> Мне там никакие JS-формы не нужны.
Формы SendPulse- очень гибкий инструмент. Вы можете создать форму со своими цветами и размерами, можете сдлелать форму на прозрачном фоне, чтобы ничего не ломать. То, что форма вызывается через JavaScript, никак не сломает вам дизайн, если вы подготовите и стилизуете элемент, в который она будет вставляться (следом за тегом script).

**Comment by qzmenko** [comment]
В чём проблема?
Заинклюдьте эти файлы и всё:
```
'src/Storage/TokenStorageInterface.php',
'src/Storage/SessionStorage.php',
'src/ApiInterface.php',
'src/ApiClient.php',
```
