### ISSUE TITLE
Работа без Сomposer

### ISSUE THREAD

**Issue by jon4god** [sendpulse/sendpulse-rest-api-php#22]
Тогда уж к 
// Without Composer:
// require("your-path/sendpulse-rest-api-php/src/ApiInterface.php");
// require("your-path/sendpulse-rest-api-php/src/ApiClient.php");

в редми добавить

// require("your-path/sendpulse-rest-api-php/src/Storage/FileStorage.php");
// require("your-path/sendpulse-rest-api-php/src/Storage/TokenStorageInterface.php");
// require("your-path/sendpulse-rest-api-php/src/Storage/SessionStorage.php");
// require("your-path/sendpulse-rest-api-php/src/Storage/MemcachedStorage.php");
// require("your-path/sendpulse-rest-api-php/src/Storage/MemcacheStorage.php");

P.S. Простите за назойливость.

**Comment by burre** [comment]
Прощаем. Проверяйте.
