### ISSUE TITLE
Ошибка при отправке запроса

### ISSUE THREAD

**Issue by uchipro** [sendpulse/sendpulse-rest-api-php#41]
Можете ли вы при вызове http_build_query явно указывать в качестве разделителя '&'?

**Comment by uchipro** [comment]
В моём случае похоже, что вместо '&' из-за настроек системы используется '&amp;'. После чего при попытке получения токена возвращается {"error":"invalid_client","error_description":"Client authentication failed.","message":"Client authentication failed.","error_code":1}. Кажется, что вы не можете из запроса получить client_id или client_secret. Думаю, было бы хорошо, если бы в тексте ошибки сразу указывалось, что такой-то параметр не передан.

**Comment by sendpulse** [comment]
Пожалуйста, предоставьте пример вашего кода, который приводит к ошибке, а также ответ сервера.

**Comment by uchipro** [comment]
Создал для теста новый каталог, в нем выполнил `composer require sendpulse/rest-api`.
Создал index.php с кодом:

```
<?php

ini_set('arg_separator.output', '&amp;'); // Такая строчка используется в движке, в котором планирую использовать вашу библиотеку.

require 'vendor/autoload.php';

use Sendpulse\RestApi\ApiClient;
use Sendpulse\RestApi\Storage\FileStorage;

$SPApiClient = new ApiClient('848bc4db4a46a004d6669534100f6729', '392c407612e81862b1302a77848e3848');
```
Запускаю и получаю результат:

```
php index.php 
PHP Fatal error:  Uncaught Exception: Could not connect to api, check your ID and SECRET in /tmp/sendpulse/vendor/sendpulse/rest-api/src/ApiClient.php:63
Stack trace:
#0 /tmp/sendpulse/index.php(10): Sendpulse\RestApi\ApiClient->__construct('848bc4db4a46a00...', '392c407612e8186...')
#1 {main}
  thrown in /tmp/sendpulse/vendor/sendpulse/rest-api/src/ApiClient.php on line 63
```
В то же время если выполнить curl с теми же данными с той же машины:

```
curl -d "grant_type=client_credentials&client_id=848bc4db4a46a004d6669534100f6729&client_secret=392c407612e81862b1302a77848e3848" -X POST https://api.sendpulse.com/oauth/access_token
```
возвращается:
```
{"access_token":"7N3B9aMhA0UFt3CsnDnHqW0HSlErJrxzTLFms8b0","token_type":"Bearer","expires_in":3600}
```

**Comment by burre** [comment]
Мы не поддерживаем работу с разделителем, который вы используете в коде.
