### ISSUE TITLE
{"is_error":true,"http_code":500}

### ISSUE THREAD

**Issue by mikhailrepka** [sendpulse/sendpulse-rest-api-php#9]
Пытаюсь добавить email через апи, всё вроде верно сделал, но вижу ответ

> {"is_error":true,"http_code":500}

Нашел коды ошибок в документации, там нет 500, только 400 и 502, между ними ничего нет.
Плиз хелп ми.

вот код:
`$sp = new SendpulseApi($config->id, $config->secret, 'file');`
`$bookid = '917511';`
`$email = 'test@test.org';`
`$name = 'Test Test';`
`$emails = array(`
`	'email' => $email,`
`	'status' => "0",`
`	'variables' => array(`
`		'имя' => $name`
`	)`
`);`
`$result = $sp->addEmails($bookid,$emails);`

**Comment by dshemendiuk** [comment]
$emails это массив отдельных итемов-контактов. 
А контакт включает в себя сам email + переменные. 

```
$emails = array(
    array(
        'email' => $email,
	'variables' => array(
	    'имя' => $name
	 )
    ),
    array(
        'email' => $email2,
	'variables' => array(
	    'имя' => $name2
	 )
    )
);
```

**Comment by mikhailrepka** [comment]
То есть, чтобы добавить один email в базу: нужно отправить
```php
$emails = array(
    array(
        "email" => $email,
            "status" => "0",
            "variables" => array(
                "имя" => $name,
                "телефон" => $phone
            )
    )
);
```

**Comment by dshemendiuk** [comment]
вообще, да. Только убрать поле "status" или внести его в массив переменных.
